language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  
addons:
  apt:
    packages:
      - libenchant-dev
# command to install dependencies
script:
 - python setup.py test
script: python _tests/Spellchecker.py
branches:
  only:
    - master
