language: python
python:
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
script: Spellchecker
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./travis-build
script: ./_tests

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler

sudo: false
