
language: ruby
rvm:
- 2.1


before_install:
  sudo apt-get install python3-enchant

install:
  - pip install 'git+https://github.com/rfk/pyenchant.git'
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./travis-build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache: bundler

sudo: false



# command to install dependencies
