name: Quattor
description: Quattor news and documentation
highlighter: pygments
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data, tables]
exclude: [vendor]
gems:
  - jekyll-feed
  - jekyll-redirect-from
